<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstracta" nsURI="abstracta" nsPrefix="abstracta">
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paquetes" upperBound="-1"
        eType="#//MKJPaquete" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaTodasLasClases" upperBound="-1"
        eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaTodosLosPaquetes"
        upperBound="-1" eType="#//MKJPaquete"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJPaquete">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paquetes" upperBound="-1"
        eType="#//MKJPaquete" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clases" upperBound="-1"
        eType="#//MKJClase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJClase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//MKJAtributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metodos" upperBound="-1"
        eType="#//MKJMetodo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relaciones" upperBound="-1"
        eType="#//MKJRelacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJAtributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJMetodo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retorno" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaParametros" upperBound="-1"
        eType="#//MKJAtributo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidad1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidad2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rol1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rol2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navegabilidad1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navegabilidad2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MKJClase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MHJAsociacion" eSuperTypes="#//MKJRelacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="MKJContainment" eSuperTypes="#//MKJRelacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="MKJAgregacion" eSuperTypes="#//MKJRelacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="MKJHerencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MKJClase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MKJClase"/>
  </eClassifiers>
</ecore:EPackage>
