<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="concreta" nsURI="concreta" nsPrefix="concreta">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaDiagramas" upperBound="-1"
        eType="#//MKJDiagramaClases" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJDiagramaClases">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaClases" upperBound="-1"
        eType="#//MKJClase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaPaquetes" upperBound="-1"
        eType="#//MKJPaquete" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaAsociaciones" upperBound="-1"
        eType="#//MKJAsociacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaConteiments" upperBound="-1"
        eType="#//MKJConteinment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaAgregaciones" upperBound="-1"
        eType="#//MKJAgregacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaHerencias" upperBound="-1"
        eType="#//MKJHerencia" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaInterfaces" upperBound="-1"
        eType="#//MKJInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJPaquete">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="232,232,232"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJClase">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="118,255,102"/>
      <details key="border.color" value="69,143,60"/>
      <details key="margin" value="1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identificador" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//MKJAtributo" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metodos" upperBound="-1"
        eType="#//MKJMetodo" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
        <details key="collapsible" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJAtributo">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="border.color" value="118,255,102"/>
      <details key="color" value="118,255,102"/>
      <details key="figure" value="rectangle"/>
      <details key="border.width" value="1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foreignKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJMetodo">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="border.color" value="118,255,102"/>
      <details key="color" value="118,255,102"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semantics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametros" upperBound="-1"
        eType="#//MKJAtributo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidad1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidad2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rol1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rol2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navegabilidad1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navegabilidad2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJAsociacion" eSuperTypes="#//MKJRelacion">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MKJClase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJConteinment" eSuperTypes="#//MKJRelacion">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="filledrhomb"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MKJClase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJAgregacion" eSuperTypes="#//MKJRelacion">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="rhomb"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MKJClase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJHerencia">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="closedarrow"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MKJClase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MKJInterface">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="closedarrow"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MKJClase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MKJClase"/>
  </eClassifiers>
</ecore:EPackage>
